# Default values for alertmanager-bot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: metalmatze/alertmanager-bot
  pullPolicy: IfNotPresent
  tag: "0.4.3"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

alertmanager:
  args:
    - --alertmanager.url=http://alertmanager-operated:9093
    - --log.level=info
    - --store=bolt
    - --bolt.path=/tmp/bot.db
  secret:
    # You can get your ID from @userinfobot.
    # In case of several admin, use following format: "111\n222\n333"
    admin: null
    # Token to access the HTTP API provided by @BotFather
    token: null

env: {}

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 25m
    memory: 64Mi
