apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmanager-bot.name" . }}
  labels:
    {{- include "alertmanager-bot.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $name, $value := .Values.alertmanager.secret }}
  {{- if not (empty $value) }}
    {{ $name }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
